# Install any missing plugins
required_plugins = %w( vagrant-vbguest vagrant-proxyconf vagrant-registration vagrant-hostsupdater )
plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Dir.mkdir './.shared/' unless File.exists?('./.shared/')

Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel8"
  config.vm.hostname = "nexus-rhel8.vm"
  config.vm.network :private_network, ip: "10.4.1.8"

  config.vbguest.auto_update = true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end

  config.proxy.enabled = true
  config.proxy.http = ENV['http_proxy']
  config.proxy.https = ENV['https_proxy']
  config.proxy.no_proxy = "localhost,127.0.0.1"

  # RHSM BITS using the vagrant-registration plugin
  config.registration.proxy = ENV['http_proxy']
  config.registration.username = ENV['RHSM_USERNAME']
  config.registration.password = ENV['RHSM_PASSWORD']
  config.registration.unregister_on_halt = false

  config.vm.synced_folder "./.shared/", "/shared", type: "virtualbox"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/playbook.yml"
  end
end
