---
- name: Nexus
  hosts: all
  become: yes
  environment:
    no_proxy: 127.0.0.1, localhost

  vars:
    nexus_timezone: 'US/Eastern'
    nexus_admin_password: "admin123"
    nexus_public_hostname: "{{ ansible_facts['fqdn'] }}"
    nexus_download_url: http://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3
    nexus_version: '3.34.1-01'
    nexus_download_dir: '/home/vagrant'
    nexus_audit_enabled: true
    httpd_setup_enable: true
    httpd_copy_ssl_files: false
    httpd_ssl_cert_file_location: "/etc/pki/tls/certs/{{ nexus_public_hostname }}.crt"
    httpd_ssl_cert_key_location: "/etc/pki/tls/private/{{ nexus_public_hostname }}.key"
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse
      - name: company-project-deploy
        description: 'Deployments to company-project'
        repository: company-project
        actions:
          - add
          - edit
    nexus_roles:
      - id: Developpers # maps to the LDAP group
        name: developers
        description: All developers
        privileges:
          - nx-search-read
          - all-repos-read
          - company-project-deploy
        roles: []
    nexus_local_users:
      - username: jenkins # used as key to update
        first_name: Jenkins
        last_name: CI
        email: support@ctc.com
        password: "s3cr3t"
        roles:
          - Developpers # role ID here
    nexus_blobstores:
      - name: company-artifacts
        path: /var/nexus/blobs/company-artifacts
    nexus_scheduled_tasks:
      - name: compact-blobstore
        cron: '0 0 22 * * ?'
        typeId: blobstore.compact
        taskProperties:
          blobstoreName: 'company-artifacts'
    nexus_repos_maven_proxy:
      - name: central
        remote_url: 'https://repo1.maven.org/maven2/'
        layout_policy: permissive
    nexus_repos_maven_hosted:
      - name: company-project
        version_policy: mixed
        write_policy: allow
        blob_store: company-artifacts
    nexus_repos_maven_group:
      - name: public
        member_repos:
          - central
    # Yum. Change nexus_config_yum to true for create yum repository
    nexus_config_yum: true
    nexus_repos_yum_hosted:
      - name: private_yum_centos_7
        repodata_depth: 1
    nexus_repos_yum_proxy:
      - name: epel_centos_7_x86_64
        remote_url: http://download.fedoraproject.org/pub/epel/7/x86_64
        maximum_component_age: -1
        maximum_metadata_age: -1
        negative_cache_ttl: 60
      - name: centos-7-os-x86_64
        remote_url: http://mirror.centos.org/centos/7/os/x86_64/
        maximum_component_age: -1
        maximum_metadata_age: -1
        negative_cache_ttl: 60
    nexus_repos_yum_group:
      - name: yum_all
        member_repos:
          - private_yum_centos_7
          - epel_centos_7_x86_64
          - centos-7-os-x86_64

  roles:
    - role: system
      tags: ['system']
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
      tags: ["geerlingguy.java"]
    - role: geerlingguy.apache
      apache_create_vhosts: no
      apache_remove_default_vhost: true
      tags: ["geerlingguy.apache"]
    - role: ansible-thoteam.nexus3-oss
      tags: ['ansible-thoteam.nexus3-oss']
    - role: nexus-pro
      tags: ['nexus-pro']
