---
- name: Nexus
  hosts: all
  become: yes
  environment:
    no_proxy: "127.0.0.1,localhost"

  vars:
    nexus_timezone: 'US/Eastern'
    nexus_admin_password: "admin123"
    nexus_public_hostname: "{{ ansible_facts['fqdn'] }}"
    nexus_download_url: http://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3
    nexus_version: '3.35.0-02'
    nexus_download_dir: '/home/vagrant'
    nexus_delete_default_repos: true
    nexus_audit_enabled: true
    httpd_setup_enable: true
    httpd_copy_ssl_files: false
    httpd_ssl_cert_file_location: "/etc/pki/tls/certs/{{ nexus_public_hostname }}.crt"
    httpd_ssl_cert_key_location: "/etc/pki/tls/private/{{ nexus_public_hostname }}.key"
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse
      - name: company-project-deploy
        description: 'Deployments to company-project'
        repository: company-project
        actions:
          - add
          - edit
    nexus_roles:
      - id: Developers # maps to the LDAP group
        name: developers
        description: All developers
        privileges:
          - nx-search-read
          - all-repos-read
          - company-project-deploy
        roles: []
    nexus_local_users:
      - username: jenkins # used as key to update
        first_name: Jenkins
        last_name: CI
        email: support@ctc.com
        password: "s3cr3t"
        roles:
          - Developers # role ID here
    nexus_blobstores:
      - name: company-artifacts
        path: /var/nexus/blobs/company-artifacts
    nexus_scheduled_tasks:
      - name: compact-blobstore
        cron: '0 0 22 * * ?'
        typeId: blobstore.compact
        taskProperties:
          blobstoreName: 'company-artifacts'
    nexus_config_yum: true
    nexus_config_pypi: true
    nexus_repos_yum_hosted:
      - name: rhel7-hosted
        blob_store: company-artifacts
        repodata_depth: 3
      - name: rhel8-hosted
        blob_store: company-artifacts
        repodata_depth: 4
    nexus_repos_pypi_hosted:
      - name: pypi-hosted
        blob_store: company-artifacts
    nexus_repos_yum_group:
      - name: yum-all
        member_repos:
          - epel7-proxy
          - rhel7-proxy
          - rhel8-proxy
          - rhel7-hosted
          - rhel8-hosted
    nexus_repos_pypi_group:
      - name: pypi-all
        member_repos:
          - pypi-hosted
          - pypi-proxy

  roles:
    - role: system
      tags: ['system']
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
      tags: ["geerlingguy.java"]
    - role: geerlingguy.apache
      apache_create_vhosts: no
      apache_remove_default_vhost: true
      tags: ["geerlingguy.apache"]
    - role: ansible-thoteam.nexus3-oss
      tags: ['ansible-thoteam.nexus3-oss']
    - role: nexus-pro
      tags: ['nexus-pro']
